# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ragios}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Sharpe"]
  s.date = %q{2009-12-14}
  s.default_executable = %q{check_ragios.rb}
  s.description = %q{Meh}
  s.email = %q{tim.sharpe@anchor.com.au}
  s.executables = ["check_ragios.rb"]
  s.files = [
    "Rakefile",
     "VERSION",
     "lib/ragios.rb",
     "ragios.gemspec"
  ]
  s.homepage = %q{http://github.com/rodjek/ragios}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Resque + Nagios == Win?}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

